[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get -y update && apt-get -y upgrade && apt-get -y install libssl-dev:$CROSS_DEB_ARCH pkg-config"
]

[target.x86_64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get -y update && apt-get -y upgrade && apt-get -y install libssl-dev:$CROSS_DEB_ARCH pkg-config"
]
